# Parte 1 — Conhecendo os dados

In [48]:
import pandas as pd

In [49]:
dados = pd.read_csv("/content/monitoramento_industrial_5000.csv", sep=',')

In [50]:
dados.head()

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
0,1,2026-03-12,Usinagem,MAQ-01,Noite,78.7,5.02,8.41,21.9,1516,154,4,0,51.9,Operando
1,2,2026-01-02,Embalagem,MAQ-19,Tarde,58.5,2.02,4.89,9.2,1114,303,0,4,38.9,Operando
2,3,2026-04-07,Embalagem,MAQ-18,Manha,61.4,2.28,4.29,7.2,978,309,2,0,37.0,Operando
3,4,2026-04-01,Pintura,MAQ-06,Tarde,75.0,2.36,7.19,19.7,1049,186,5,0,35.9,Operando
4,5,2026-02-28,Montagem,MAQ-11,Manha,66.5,1.07,5.56,13.6,1593,209,3,0,33.0,Operando

In [51]:
dados.tail()

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
4995,4996,2026-02-22,Montagem,MAQ-17,Tarde,56.0,2.75,6.24,13.6,880,289,0,0,39.8,Operando
4996,4997,2026-06-05,Embalagem,MAQ-18,Noite,52.2,2.07,4.80,15.4,917,270,0,0,29.5,Operando
4997,4998,2026-02-09,Usinagem,MAQ-01,Noite,77.5,4.39,8.52,19.8,1907,148,2,0,57.4,Operando
4998,4999,2026-04-02,Usinagem,MAQ-14,Manha,67.5,6.60,7.35,10.2,1677,214,6,46,47.5,Parada
4999,5000,2026-05-03,Pintura,MAQ-16,Tarde,73.4,2.29,5.62,17.1,828,179,3,0,53.5,Operando

In [52]:
dados.sample(5)

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
2594,2595,2026-04-29,Embalagem,MAQ-11,Noite,62.3,1.83,5.91,12.6,989,219,5,0,36.4,Operando
4158,4159,2026-02-24,Embalagem,MAQ-15,Noite,62.5,2.59,4.79,10.8,1439,321,0,0,28.5,Operando
4926,4927,2026-01-03,Pintura,MAQ-16,Manha,67.7,2.64,7.50,12.4,1230,261,3,0,38.0,Operando
360,361,2026-03-29,Pintura,MAQ-14,Noite,63.6,1.03,5.17,15.5,927,181,1,0,29.0,Operando
3291,3292,2026-06-18,Usinagem,MAQ-05,Manha,69.1,2.02,6.04,19.1,1660,155,2,0,35.2,Operando

In [53]:
dados.columns

Index(['id_registro', 'data', 'setor', 'maquina', 'turno', 'temperatura_c',
       'vibracao_mm_s', 'pressao_bar', 'corrente_a', 'velocidade_rpm',
       'producao_unidades', 'defeitos', 'tempo_parada_min', 'consumo_kwh',
       'status_maquina'],
      dtype='object')

In [54]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_registro        5000 non-null   int64
 1   data               5000 non-null   object
 2   setor              5000 non-null   object
 3   maquina            5000 non-null   object
 4   turno              5000 non-null   object
 5   temperatura_c      5000 non-null   float64
 6   vibracao_mm_s      4909 non-null   float64
 7   pressao_bar        4925 non-null   float64
 8   corrente_a         4931 non-null   float64
 9   velocidade_rpm     5000 non-null   int64
 10  producao_unidades  5000 non-null   int64
 11  defeitos           5000 non-null   int64
 12  tempo_parada_min   5000 non-null   int64
 13  consumo_kwh        4943 non-null   float64
 14  status_maquina     5000 non-null   object
dtypes: float64(5), int64(5), object(5)
memory usage: 586.1+ KB

# Parte 2 — Selecionando informações

In [55]:
col = ['temperatura_c']
dados[col]

      temperatura_c
0              78.7
1              58.5
2              61.4
3              75.0
4              66.5
...             ...
4995           56.0
4996           52.2
4997           77.5
4998           67.5
4999           73.4

[5000 rows x 1 columns]

In [56]:
col = ['maquina', 'setor', 'temperatura_c', 'status_maquina']
dados[col]

     maquina      setor  temperatura_c status_maquina
0     MAQ-01   Usinagem           78.7       Operando
1     MAQ-19  Embalagem           58.5       Operando
2     MAQ-18  Embalagem           61.4       Operando
3     MAQ-06    Pintura           75.0       Operando
4     MAQ-11   Montagem           66.5       Operando
...      ...        ...            ...            ...
4995  MAQ-17   Montagem           56.0       Operando
4996  MAQ-18  Embalagem           52.2       Operando
4997  MAQ-01   Usinagem           77.5       Operando
4998  MAQ-14   Usinagem           67.5         Parada
4999  MAQ-16    Pintura           73.4       Operando

[5000 rows x 4 columns]

# Parte 3 — Filtros

## Filtro 1 — Temperatura elevada

In [57]:
mask = dados['temperatura_c'] >= 80
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
8,9,2026-03-03,Pintura,MAQ-08,Manha,83.0,0.86,7.39,17.1,1426,233,3,0,39.4,Alerta
18,19,2026-06-13,Usinagem,MAQ-11,Manha,81.3,4.09,5.64,20.2,1732,173,1,0,61.0,Operando
21,22,2026-02-27,Pintura,MAQ-10,Manha,83.0,2.72,6.59,11.7,1467,236,5,0,37.7,Alerta
22,23,2026-03-09,Pintura,MAQ-06,Noite,82.0,NaN,5.61,20.1,672,238,2,14,51.8,Alerta
32,33,2026-06-16,Usinagem,MAQ-12,Manha,96.5,5.77,7.34,18.3,1858,246,11,82,43.2,Parada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,4962,2026-06-01,Usinagem,MAQ-15,Noite,82.0,5.36,7.41,20.6,1645,202,5,0,37.6,Alerta
4969,4970,2026-02-17,Usinagem,MAQ-13,Noite,88.5,2.23,9.71,14.8,2104,182,10,0,37.5,Alerta
4978,4979,2026-04-08,Usinagem,MAQ-13,Tarde,88.1,5.14,7.49,17.9,1624,167,8,0,56.4,Alerta
4985,4986,2026-04-10,Usinagem,MAQ-13,Tarde,81.7,7.33,6.07,22.8,1778,130,8,56,46.5,Parada
4992,4993,2026-05-21,Usinagem,MAQ-02,Noite,80.5,4.47,4.71,21.9,1843,163,4,0,50.8,Operando

## Filtro 2 — Máquinas em alerta

In [58]:
mask = dados['status_maquina'] == "Alerta"
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
8,9,2026-03-03,Pintura,MAQ-08,Manha,83.0,0.86,7.39,17.1,1426,233,3,0,39.4,Alerta
21,22,2026-02-27,Pintura,MAQ-10,Manha,83.0,2.72,6.59,11.7,1467,236,5,0,37.7,Alerta
22,23,2026-03-09,Pintura,MAQ-06,Noite,82.0,NaN,5.61,20.1,672,238,2,14,51.8,Alerta
39,40,2026-05-17,Pintura,MAQ-01,Noite,82.0,2.37,6.70,17.7,1200,238,0,0,35.1,Alerta
49,50,2026-03-29,Usinagem,MAQ-09,Tarde,76.2,5.84,6.62,19.4,1658,166,9,0,59.4,Alerta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4940,4941,2026-06-08,Usinagem,MAQ-01,Tarde,78.6,5.87,7.50,20.9,1721,225,6,0,37.4,Alerta
4961,4962,2026-06-01,Usinagem,MAQ-15,Noite,82.0,5.36,7.41,20.6,1645,202,5,0,37.6,Alerta
4969,4970,2026-02-17,Usinagem,MAQ-13,Noite,88.5,2.23,9.71,14.8,2104,182,10,0,37.5,Alerta
4978,4979,2026-04-08,Usinagem,MAQ-13,Tarde,88.1,5.14,7.49,17.9,1624,167,8,0,56.4,Alerta
4986,4987,2026-06-08,Usinagem,MAQ-09,Manha,78.7,6.21,8.95,13.0,1803,166,8,0,57.5,Alerta

## Filtro 3 — Setor específico

In [59]:
mask = dados['setor'] == "Usinagem"
dados[mask][['setor']]

         setor
0     Usinagem
10    Usinagem
17    Usinagem
18    Usinagem
27    Usinagem
...        ...
4985  Usinagem
4986  Usinagem
4992  Usinagem
4997  Usinagem
4998  Usinagem

[1317 rows x 1 columns]

## Filtro 4 — Temperatura crítica na Usinagem

In [60]:
mask = (dados['setor'] == "Usinagem") & (dados['temperatura_c'] >= 85)
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
32,33,2026-06-16,Usinagem,MAQ-12,Manha,96.5,5.77,7.34,18.3,1858,246,11,82,43.2,Parada
56,57,2026-05-08,Usinagem,MAQ-20,Noite,88.2,1.39,7.22,15.1,1908,147,7,0,50.5,Alerta
69,70,2026-06-27,Usinagem,MAQ-20,Noite,87.8,4.10,7.73,17.0,1636,168,11,0,48.8,Alerta
78,79,2026-02-14,Usinagem,MAQ-17,Noite,92.2,4.77,8.32,17.7,1659,143,11,16,55.8,Alerta
99,100,2026-01-12,Usinagem,MAQ-01,Manha,94.7,6.64,6.55,17.7,2028,136,10,47,42.5,Parada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,4912,2026-01-03,Usinagem,MAQ-17,Noite,87.6,1.22,6.50,20.8,1697,186,8,0,38.1,Alerta
4925,4926,2026-01-30,Usinagem,MAQ-13,Noite,93.8,3.59,7.14,18.8,1694,187,3,85,43.6,Parada
4956,4957,2026-05-27,Usinagem,MAQ-08,Tarde,90.5,3.86,6.74,16.2,1758,243,7,33,49.0,Parada
4969,4970,2026-02-17,Usinagem,MAQ-13,Noite,88.5,2.23,9.71,14.8,2104,182,10,0,37.5,Alerta
4978,4979,2026-04-08,Usinagem,MAQ-13,Tarde,88.1,5.14,7.49,17.9,1624,167,8,0,56.4,Alerta

## Filtro 5 — Problemas durante o turno da noite

In [61]:
mask = (dados['turno'] == "Noite") & (dados['vibracao_mm_s'] >= 5.5)
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
96,97,2026-05-27,Usinagem,MAQ-12,Noite,67.5,6.19,5.80,16.2,2041,174,7,0,62.3,Alerta
110,111,2026-01-21,Usinagem,MAQ-10,Noite,73.0,5.53,7.05,22.6,1945,212,5,0,60.7,Alerta
167,168,2026-05-11,Usinagem,MAQ-08,Noite,80.9,7.17,7.13,19.2,1856,118,5,63,63.3,Parada
183,184,2026-03-23,Usinagem,MAQ-06,Noite,91.4,7.65,5.85,18.9,2180,190,8,31,46.1,Parada
189,190,2026-06-20,Usinagem,MAQ-05,Noite,84.9,6.03,7.95,19.5,1598,175,8,0,41.5,Alerta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4726,4727,2026-01-18,Usinagem,MAQ-13,Noite,70.2,5.90,7.44,12.6,1888,161,7,18,51.0,Alerta
4757,4758,2026-05-19,Usinagem,MAQ-20,Noite,78.7,7.16,7.02,20.2,1489,146,9,82,42.5,Parada
4793,4794,2026-01-17,Usinagem,MAQ-01,Noite,89.1,6.95,6.28,17.9,2005,230,10,10,44.5,Alerta
4819,4820,2026-05-25,Usinagem,MAQ-17,Noite,80.2,5.63,6.58,19.1,2077,157,6,0,49.8,Alerta
4843,4844,2026-01-05,Usinagem,MAQ-19,Noite,80.8,6.05,6.27,15.9,1473,218,5,0,51.3,Alerta

## Filtro 6 — Máquinas paradas

In [62]:
mask = (dados['status_maquina'] == "Parada") & (dados['tempo_parada_min'] >= 30)
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
32,33,2026-06-16,Usinagem,MAQ-12,Manha,96.5,5.77,7.34,18.3,1858,246,11,82,43.2,Parada
99,100,2026-01-12,Usinagem,MAQ-01,Manha,94.7,6.64,6.55,17.7,2028,136,10,47,42.5,Parada
143,144,2026-05-18,Usinagem,MAQ-12,Noite,90.8,1.44,5.87,20.3,1974,145,6,61,43.3,Parada
163,164,2026-01-18,Usinagem,MAQ-01,Noite,86.6,5.24,7.16,26.6,1553,135,8,61,52.4,Parada
167,168,2026-05-11,Usinagem,MAQ-08,Noite,80.9,7.17,7.13,19.2,1856,118,5,63,63.3,Parada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4925,4926,2026-01-30,Usinagem,MAQ-13,Noite,93.8,3.59,7.14,18.8,1694,187,3,85,43.6,Parada
4952,4953,2026-03-17,Pintura,MAQ-12,Tarde,93.2,1.26,6.28,12.7,907,242,4,50,44.5,Parada
4956,4957,2026-05-27,Usinagem,MAQ-08,Tarde,90.5,3.86,6.74,16.2,1758,243,7,33,49.0,Parada
4985,4986,2026-04-10,Usinagem,MAQ-13,Tarde,81.7,7.33,6.07,22.8,1778,130,8,56,46.5,Parada
4998,4999,2026-04-02,Usinagem,MAQ-14,Manha,67.5,6.60,7.35,10.2,1677,214,6,46,47.5,Parada

## Filtro 7 — Alta produção

In [63]:
mask = dados['producao_unidades'] >= 300
dados[mask][['maquina', 'setor', 'turno', 'producao_unidades']]

     maquina      setor  turno  producao_unidades
1     MAQ-19  Embalagem  Tarde                303
2     MAQ-18  Embalagem  Manha                309
13    MAQ-10  Embalagem  Tarde                308
23    MAQ-12   Montagem  Tarde                308
24    MAQ-13  Embalagem  Noite                317
...      ...        ...    ...                ...
4980  MAQ-14   Montagem  Manha                359
4983  MAQ-16   Montagem  Manha                320
4984  MAQ-02  Embalagem  Tarde                365
4988  MAQ-08    Pintura  Tarde                333
4991  MAQ-14   Montagem  Tarde                329

[601 rows x 4 columns]

## Filtro 8 — Produção com poucos defeitos

In [64]:
mask = (dados['producao_unidades'] >= 280) & (dados['defeitos'] == 0)
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
1,2,2026-01-02,Embalagem,MAQ-19,Tarde,58.5,2.02,4.89,9.2,1114,303,0,4,38.9,Operando
13,14,2026-06-28,Embalagem,MAQ-10,Tarde,61.8,4.22,4.69,7.3,957,308,0,0,33.2,Operando
59,60,2026-06-22,Embalagem,MAQ-12,Manha,51.6,2.02,5.46,13.4,904,315,0,0,26.8,Operando
68,69,2026-06-03,Embalagem,MAQ-02,Tarde,56.9,2.30,4.89,10.9,722,295,0,0,24.5,Operando
94,95,2026-04-10,Montagem,MAQ-16,Noite,66.5,2.44,6.00,8.4,1416,289,0,0,25.2,Operando
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4960,4961,2026-06-02,Embalagem,MAQ-12,Manha,51.3,0.30,5.78,8.8,1129,406,0,0,30.9,Operando
4964,4965,2026-02-02,Embalagem,MAQ-19,Noite,60.6,1.33,5.10,8.0,910,363,0,0,37.3,Operando
4976,4977,2026-04-08,Montagem,MAQ-16,Tarde,68.8,3.45,5.19,14.2,1381,303,0,0,36.9,Operando
4988,4989,2026-04-28,Pintura,MAQ-08,Tarde,65.4,3.38,6.03,16.5,1007,333,0,0,35.1,Operando
4995,4996,2026-02-22,Montagem,MAQ-17,Tarde,56.0,2.75,6.24,13.6,880,289,0,0,39.8,Operando

## Filtro 9 — Condição elétrica de atenção

In [65]:
mask = (dados['corrente_a'] >= 22) & (dados['temperatura_c'] >= 82)
dados[mask][['maquina', 'temperatura_c', 'corrente_a', 'status_maquina']]

     maquina  temperatura_c  corrente_a status_maquina
163   MAQ-01           86.6        26.6         Parada
410   MAQ-18           84.3        24.9         Alerta
459   MAQ-01           95.1        25.2         Parada
543   MAQ-10           95.3        26.0         Parada
655   MAQ-04           88.2        22.8         Alerta
701   MAQ-07           94.1        24.4         Parada
776   MAQ-19           89.3        25.7         Parada
784   MAQ-03           84.8        22.0         Alerta
1067  MAQ-20           88.0        23.3         Alerta
1076  MAQ-17           88.8        22.3         Alerta
1132  MAQ-01           82.0        25.2         Parada
1329  MAQ-05           83.3        22.5         Alerta
1404  MAQ-16           82.1        23.6         Alerta
1484  MAQ-14           93.2        25.1         Alerta
1552  MAQ-19           83.5        25.2         Parada
1555  MAQ-11           82.2        22.2         Alerta
1601  MAQ-19           83.1        23.0         Alerta
1695  MAQ-02           82.9        22.9         Alerta
1778  MAQ-10           98.3        22.0         Parada
1814  MAQ-07           84.5        24.7         Alerta
1869  MAQ-03           86.5        23.8         Alerta
1937  MAQ-13           92.2        22.8         Parada
2050  MAQ-09           85.9        25.2         Alerta
2119  MAQ-16           85.9        24.5         Alerta
2123  MAQ-07           82.6        22.8         Alerta
2155  MAQ-02           87.6        22.1         Alerta
2223  MAQ-07           86.1        23.1         Alerta
2291  MAQ-19           91.5        26.5         Parada
2336  MAQ-14           85.5        25.3         Parada
2358  MAQ-13           82.0        25.0         Alerta
2394  MAQ-16           87.7        23.8         Alerta
2500  MAQ-20           94.9        23.5         Parada
2533  MAQ-14           87.4        23.8         Alerta
2689  MAQ-07           97.0        23.7         Parada
2713  MAQ-18           97.3        23.1         Parada
2874  MAQ-20           91.1        24.5         Parada
2876  MAQ-17           93.0        22.9         Parada
3129  MAQ-17           97.7        24.2         Parada
3198  MAQ-03           94.0        23.7         Parada
3220  MAQ-09           86.0        22.3         Alerta
3425  MAQ-18           82.6        23.0         Alerta
3443  MAQ-05           91.3        22.1         Parada
3447  MAQ-05           85.6        22.0         Alerta
3449  MAQ-02           84.1        24.2         Alerta
3527  MAQ-02           84.0        26.8         Parada
3559  MAQ-10           89.7        24.0         Alerta
3561  MAQ-01           86.5        25.6         Parada
3761  MAQ-10           89.3        22.3         Alerta
3792  MAQ-05           92.3        22.4         Parada
3812  MAQ-13           83.0        22.6         Alerta
3961  MAQ-15           83.5        23.2         Parada
4079  MAQ-10           98.1        27.4         Parada
4094  MAQ-14           85.1        22.1         Alerta
4199  MAQ-04           85.7        22.7         Alerta
4291  MAQ-13           83.4        25.5         Parada
4427  MAQ-10           88.1        22.6         Alerta
4547  MAQ-10           85.1        23.2         Alerta
4712  MAQ-02           85.3        23.5         Alerta
4748  MAQ-15           88.9        23.3         Alerta
4809  MAQ-13           91.4        22.8         Parada

## Filtro 10 — Condição por dois setores

In [66]:
mask = (dados['setor'] == "Montagem") | (dados['setor'] >= "Pintura")
dados[mask]

,id_registro,data,setor,maquina,turno,temperatura_c,vibracao_mm_s,pressao_bar,corrente_a,velocidade_rpm,producao_unidades,defeitos,tempo_parada_min,consumo_kwh,status_maquina
0,1,2026-03-12,Usinagem,MAQ-01,Noite,78.7,5.02,8.41,21.9,1516,154,4,0,51.9,Operando
3,4,2026-04-01,Pintura,MAQ-06,Tarde,75.0,2.36,7.19,19.7,1049,186,5,0,35.9,Operando
4,5,2026-02-28,Montagem,MAQ-11,Manha,66.5,1.07,5.56,13.6,1593,209,3,0,33.0,Operando
5,6,2026-05-30,Pintura,MAQ-19,Tarde,64.6,1.75,6.87,19.2,1146,215,0,0,40.3,Operando
7,8,2026-06-10,Montagem,MAQ-17,Manha,58.4,2.27,6.89,11.7,1269,244,4,0,25.3,Operando
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,4995,2026-05-20,Pintura,MAQ-07,Manha,66.4,2.91,7.46,14.1,1446,189,0,0,50.7,Operando
4995,4996,2026-02-22,Montagem,MAQ-17,Tarde,56.0,2.75,6.24,13.6,880,289,0,0,39.8,Operando
4997,4998,2026-02-09,Usinagem,MAQ-01,Noite,77.5,4.39,8.52,19.8,1907,148,2,0,57.4,Operando
4998,4999,2026-04-02,Usinagem,MAQ-14,Manha,67.5,6.60,7.35,10.2,1677,214,6,46,47.5,Parada
4999,5000,2026-05-03,Pintura,MAQ-16,Tarde,73.4,2.29,5.62,17.1,828,179,3,0,53.5,Operando

# Parte 4 — Valores ausentes

In [67]:
dados.isna().sum()

id_registro           0
data                  0
setor                 0
maquina               0
turno                 0
temperatura_c         0
vibracao_mm_s        91
pressao_bar          75
corrente_a           69
velocidade_rpm        0
producao_unidades     0
defeitos              0
tempo_parada_min      0
consumo_kwh          57
status_maquina        0
dtype: int64

In [68]:
(dados.isna().sum()/dados.shape[0])*100

id_registro          0.00
data                 0.00
setor                0.00
maquina              0.00
turno                0.00
temperatura_c        0.00
vibracao_mm_s        1.82
pressao_bar          1.50
corrente_a           1.38
velocidade_rpm       0.00
producao_unidades    0.00
defeitos             0.00
tempo_parada_min     0.00
consumo_kwh          1.14
status_maquina       0.00
dtype: float64

# Parte 5 — Criando uma classificação

In [70]:
dados['faixa_temperatura'] = "Normal"
mask_atencao = dados['temperatura_c'] >= 75
mask_critica = dados['temperatura_c'] >= 90
dados.loc[mask_atencao, 'faixa_temperatura'] = 'Atencao'
dados.loc[mask_critica, 'faixa_temperatura'] = 'Critica'
dados['faixa_temperatura'].unique()

array(['Atencao', 'Normal', 'Critica'], dtype=object)

# Parte 6 — Resumindo os dados

In [71]:
dados.groupby('setor')['temperatura_c'].mean()

setor
Embalagem    58.308529
Montagem     62.250574
Pintura      69.971308
Usinagem     77.716021
Name: temperatura_c, dtype: float64

In [72]:
dados.groupby('turno')['temperatura_c'].mean()

turno
Manha    65.711580
Noite    68.625711
Tarde    67.096744
Name: temperatura_c, dtype: float64

# Desafio final