# Importando as Bibliotecas

In [ ]:
import pandas as pd

# Carregando o Arquivo csv

In [ ]:
dados = pd.read_csv("/content/dados_limpeza_automacao.csv", sep = ",")

In [ ]:
dados.head()

,id_registro,equipamento,situacao,temperatura_c,vibracao_mm_s,producao_pecas_h
0,1,Motor 02,manutencao,66.22,3.80,23
1,2,Motor 02,manutencao,69.33,2.83,13
2,3,Motor 01,operando,68.63,4.26,186
3,4,Robô 01,manutencao,61.83,2.09,7
4,5,Compressor 01,Em operação,67.29,2.99,386

# Conhecendo o Conjundo de Dados

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_registro       12000 non-null  int64
 1   equipamento       12000 non-null  object
 2   situacao          12000 non-null  object
 3   temperatura_c     12000 non-null  float64
 4   vibracao_mm_s     12000 non-null  float64
 5   producao_pecas_h  12000 non-null  int64
dtypes: float64(2), int64(2), object(2)
memory usage: 562.6+ KB

## Verificação por Valores Nulos

In [ ]:
dados.isna().sum()

id_registro         0
equipamento         0
situacao            0
temperatura_c       0
vibracao_mm_s       0
producao_pecas_h    0
dtype: int64

## Avaliando os valores únicos das colunas do tipo `object`

In [ ]:
dados['equipamento'].unique()

array(['Motor 02', '  Motor 02  ', 'Motor 01', ' Robô 01',
       'Compressor 01  ', '  Motor 03  ', 'Bomba 01', 'Robô 02 ',
       'Bomba 02', 'Bomba 01  ', 'Esteira 02', '  Compressor 01  ',
       '  Esteira 02  ', 'Motor 03  ', 'Esteira 01', '  Robô 02  ',
       ' Compressor 01', ' Bomba 01', ' Motor 02', '  Motor 02',
       'Esteira 02  ', 'Robô 01 ', '  Motor 03', '  Bomba 01',
       ' Esteira 02', '  Robô 01  ', 'Motor 02 ', 'Motor 01 ',
       'Esteira 01  ', '  Motor 01  ', ' Bomba 02', '  Compressor 01',
       'Compressor 01 ', 'Motor 01  ', 'Motor 03', 'Robô 02', ' Robô 02',
       '  Bomba 02  ', 'Robô 01', 'Motor 03 ', '  Robô 01', ' Esteira 01',
       'Esteira 01 ', '  Motor 01', '  Bomba 01  ', 'Compressor 01',
       ' Motor 03', ' Motor 01', '  Esteira 02', 'Robô 01  ',
       '  Esteira 01  ', 'Esteira 02 ', 'Motor 02  ', '  Bomba 02',
       'Bomba 01 ', 'Robô 02  ', 'Bomba 02  ', '  Robô 02',
       '  Esteira 01', 'Bomba 02 '], dtype=object)

In [10]:
dados['situacao'].unique()

array(['manutencao', 'operando', 'Em operação', 'parado', 'MANUTENÇÃO',
       'Desligado', 'Ligado', 'Em manutenção', 'Manut.', 'Manutenção',
       'Parado', 'Fora de operação', 'OPERANDO', 'Operando', 'PARADO'],
      dtype=object)

In [9]:
dados['equipamento'].nunique()

60

In [11]:
dados['situacao'].nunique()

15

### Valores Impossíveis

In [15]:
dados.select_dtypes(exclude = 'object').drop(columns=['id_registro']).min()

temperatura_c       41.81
vibracao_mm_s        0.20
producao_pecas_h     0.00
dtype: float64

In [16]:
dados.select_dtypes(exclude = 'object').drop(columns=['id_registro']).max()

temperatura_c        93.99
vibracao_mm_s         6.74
producao_pecas_h    420.00
dtype: float64

# Problema 01: Espaços na coluna `equipamento`

In [17]:
dados['equipamento'].str.strip()

0             Motor 02
1             Motor 02
2             Motor 01
3              Robô 01
4        Compressor 01
             ...
11995          Robô 02
11996         Bomba 01
11997       Esteira 01
11998    Compressor 01
11999         Bomba 02
Name: equipamento, Length: 12000, dtype: object

In [18]:
dados['equipamento'].str.strip().unique()

array(['Motor 02', 'Motor 01', 'Robô 01', 'Compressor 01', 'Motor 03',
       'Bomba 01', 'Robô 02', 'Bomba 02', 'Esteira 02', 'Esteira 01'],
      dtype=object)

In [19]:
dados['equipamento'].str.strip().nunique()

10

In [20]:
dados['equipamento'] = dados['equipamento'].str.strip()

In [21]:
dados['equipamento'].unique()

array(['Motor 02', 'Motor 01', 'Robô 01', 'Compressor 01', 'Motor 03',
       'Bomba 01', 'Robô 02', 'Bomba 02', 'Esteira 02', 'Esteira 01'],
      dtype=object)

# Problema 02: Valores diferentes representando a mesma informação (`situacao`)

In [22]:
dados['situacao'].value_counts()

situacao
Em manutenção       832
Em operação         830
parado              829
Manutenção          826
PARADO              816
OPERANDO            805
Parado              800
Desligado           794
manutencao          793
MANUTENÇÃO          791
Operando            789
Ligado              785
Fora de operação    779
Manut.              777
operando            754
Name: count, dtype: int64

In [29]:
mapa_situacao = {
    # Operando
    'Operando' : 'Operando', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'OPERANDO' : 'Operando',
    'operando' : 'Operando',
    'Em operação' : 'Operando',
    'Ligado' : 'Operando',
    # Parado
    'Parado' : 'Parado', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'parado' : 'Parado',
    'PARADO' : 'Parado',
    'Fora de operação' : 'Parado',
    'Desligado' : 'Parado',
    # Manutenção
    'Manutenção' : 'Manutenção', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'Em manutenção' : 'Manutenção',
    'manutencao' : 'Manutenção',
    'MANUTENÇÃO' : 'Manutenção',
    'Manut.' : 'Manutenção'
}

In [30]:
dados['situacao'].map(mapa_situacao).isna().sum()

np.int64(0)

In [34]:
# ver qual é o erro que pode ter dado(erro = np.int64(0) difetente de 0)
mask = dados['situacao'].map(mapa_situacao).isna()
dados[mask]['situacao'].unique()

array([], dtype=object)

In [31]:
dados['situacao'] = dados['situacao'].map(mapa_situacao)

In [32]:
dados['situacao'].unique()

array(['Manutenção', 'Operando', 'Parado'], dtype=object)

# Salvar a tabela com dados tratados

In [35]:
dados.to_csv('dados_limpeza_automacao_tratados.csv', index = False)