#1

In [62]:
import pandas as pd

In [63]:
dados = pd.read_csv("/content/dados_producao_200_linhas.csv", sep = ";")

In [64]:
dados.head()

   registro        data   hora  turno  pecas_produzidas
0         1  03/08/2026  08:00  Manhã            -200.0
1         2  03/08/2026  09:00  Manhã               NaN
2         3  03/08/2026  10:00  Manhã              31.0
3         4  03/08/2026  11:00  Manhã              77.0
4         5  03/08/2026  12:00  Manhã              47.0

#2

In [65]:
dados['pecas_produzidas'].isna().sum()

np.int64(10)

In [66]:
# sem processar dados
# mediana = dados['pecas_produzidas'].median()

# mediana sem impossiveis
mask = dados['pecas_produzidas'] >= 0
mediana = dados[mask]['pecas_produzidas'].median()
dados.fillna(
    {
        'pecas_produzidas' : mediana
    }, inplace=True
)

In [67]:
dados['pecas_produzidas'].isna().sum()

np.int64(0)

#3

In [69]:
(dados['pecas_produzidas'] < 0).sum()

np.int64(20)

#4

In [70]:
mask = dados['pecas_produzidas'] < 0

#5

In [71]:
dados.loc[mask, 'pecas_produzidas'] = mediana

In [72]:
(dados['pecas_produzidas'] < 0).sum()

np.int64(0)

#6

In [73]:
dados.head()

   registro        data   hora  turno  pecas_produzidas
0         1  03/08/2026  08:00  Manhã              59.0
1         2  03/08/2026  09:00  Manhã              59.0
2         3  03/08/2026  10:00  Manhã              31.0
3         4  03/08/2026  11:00  Manhã              77.0
4         5  03/08/2026  12:00  Manhã              47.0